from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *;
import booking_db as db
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(769, 419)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MainLabel = QtWidgets.QLabel(self.centralwidget)
        self.MainLabel.setGeometry(QtCore.QRect(230, 30, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Perpetua Titling MT")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.MainLabel.setFont(font)
        self.MainLabel.setObjectName("MainLabel")
        self.UserLabel = QtWidgets.QLabel(self.centralwidget)
        self.UserLabel.setGeometry(QtCore.QRect(100, 100, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.UserLabel.setFont(font)
        self.UserLabel.setObjectName("UserLabel")
        self.UserEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.UserEdit.setGeometry(QtCore.QRect(290, 100, 441, 31))
        self.UserEdit.setObjectName("UserEdit")
        self.CarLabel = QtWidgets.QLabel(self.centralwidget)
        self.CarLabel.setGeometry(QtCore.QRect(100, 170, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.CarLabel.setFont(font)
        self.CarLabel.setObjectName("CarLabel")
        self.CarEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.CarEdit.setGeometry(QtCore.QRect(290, 170, 441, 31))
        self.CarEdit.setObjectName("CarEdit")
        self.TimeLabel = QtWidgets.QLabel(self.centralwidget)
        self.TimeLabel.setGeometry(QtCore.QRect(100, 240, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.TimeLabel.setFont(font)
        self.TimeLabel.setObjectName("TimeLabel")
        self.STime = QtWidgets.QComboBox(self.centralwidget)
        self.STime.setGeometry(QtCore.QRect(290, 240, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.STime.setFont(font)
        self.STime.setObjectName("STime")
        self.STime.addItem("")
        self.STime.addItem("")
        self.STime.addItem("")
        self.STime.addItem("")
        self.STime.addItem("")
        self.STime.addItem("")
        self.STime.addItem("")
        self.STime.addItem("")
        self.STime.addItem("")
        self.STime.addItem("")
        self.STime.addItem("")
        self.STime.addItem("")
        self.STimeAM = QtWidgets.QComboBox(self.centralwidget)
        self.STimeAM.setGeometry(QtCore.QRect(410, 240, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.STimeAM.setFont(font)
        self.STimeAM.setObjectName("STimeAM")
        self.STimeAM.addItem("")
        self.STimeAM.addItem("")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(500, 240, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.ETimeAM = QtWidgets.QComboBox(self.centralwidget)
        self.ETimeAM.setGeometry(QtCore.QRect(670, 240, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ETimeAM.setFont(font)
        self.ETimeAM.setObjectName("ETimeAM")
        self.ETimeAM.addItem("")
        self.ETimeAM.addItem("")
        self.ETime = QtWidgets.QComboBox(self.centralwidget)
        self.ETime.setGeometry(QtCore.QRect(550, 240, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ETime.setFont(font)
        self.ETime.setObjectName("ETime")
        self.ETime.addItem("")
        self.ETime.addItem("")
        self.ETime.addItem("")
        self.ETime.addItem("")
        self.ETime.addItem("")
        self.ETime.addItem("")
        self.ETime.addItem("")
        self.ETime.addItem("")
        self.ETime.addItem("")
        self.ETime.addItem("")
        self.ETime.addItem("")
        self.ETime.addItem("")
        self.BookButton = QtWidgets.QPushButton(self.centralwidget)
        self.BookButton.setGeometry(QtCore.QRect(100, 320, 641, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.BookButton.setFont(font)
        self.BookButton.setObjectName("BookButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 769, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.BookButton.clicked.connect(self.insrt)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.MainLabel.setText(_translate("MainWindow", "BOOKING HERE"))
        self.UserLabel.setText(_translate("MainWindow", "USER NAME"))
        self.CarLabel.setText(_translate("MainWindow", "CAR NO"))
        self.TimeLabel.setText(_translate("MainWindow", "TIME"))
        self.STime.setItemText(0, _translate("MainWindow", "12:00"))
        self.STime.setItemText(1, _translate("MainWindow", "1:00"))
        self.STime.setItemText(2, _translate("MainWindow", "2:00"))
        self.STime.setItemText(3, _translate("MainWindow", "3:00"))
        self.STime.setItemText(4, _translate("MainWindow", "4:00"))
        self.STime.setItemText(5, _translate("MainWindow", "5:00"))
        self.STime.setItemText(6, _translate("MainWindow", "6:00"))
        self.STime.setItemText(7, _translate("MainWindow", "7:00"))
        self.STime.setItemText(8, _translate("MainWindow", "8:00"))
        self.STime.setItemText(9, _translate("MainWindow", "9:00"))
        self.STime.setItemText(10, _translate("MainWindow", "10:00"))
        self.STime.setItemText(11, _translate("MainWindow", "11:00"))
        self.STimeAM.setItemText(0, _translate("MainWindow", "AM"))
        self.STimeAM.setItemText(1, _translate("MainWindow", "PM"))
        self.label_4.setText(_translate("MainWindow", "TO"))
        self.ETimeAM.setItemText(0, _translate("MainWindow", "AM"))
        self.ETimeAM.setItemText(1, _translate("MainWindow", "PM"))
        self.ETime.setItemText(0, _translate("MainWindow", "12:00"))
        self.ETime.setItemText(1, _translate("MainWindow", "1:00"))
        self.ETime.setItemText(2, _translate("MainWindow", "2:00"))
        self.ETime.setItemText(3, _translate("MainWindow", "3:00"))
        self.ETime.setItemText(4, _translate("MainWindow", "4:00"))
        self.ETime.setItemText(5, _translate("MainWindow", "5:00"))
        self.ETime.setItemText(6, _translate("MainWindow", "6:00"))
        self.ETime.setItemText(7, _translate("MainWindow", "7:00"))
        self.ETime.setItemText(8, _translate("MainWindow", "8:00"))
        self.ETime.setItemText(9, _translate("MainWindow", "9:00"))
        self.ETime.setItemText(10, _translate("MainWindow", "10:00"))
        self.ETime.setItemText(11, _translate("MainWindow", "11:00"))
        self.BookButton.setText(_translate("MainWindow", "BOOK SLAOT"))


    @pyqtSlot()
    def insrt(self):				#insert into booking table
        db.BookDB().insertData(self.UserEdit.text(),self.CarEdit.text(),self.STime.currentText(),self.ETime.currentText())






if__name__=="__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

